### ISSUE TITLE
Fit4Param example

### ISSUE THREAD

**Issue by andreafarina** [andreafarina/SOLUS#3]
@giudisciacca : bisognerebbe fissare la cartella /example/Fit4Param con un esempio funzionante che usi il toast per fittare e che importi una tua simulazione fatta con toast. Dovresti poi aggiungere un file readme.txt per spiegare velocemente cosa fa l'esempio.

**Comment by giudisciacca** [comment]
@andreafarina : Ok, provvedo appena possibile e faccio commit e push.

**Comment by andreafarina** [comment]
@giudisciacca Grazie giuseppe. Allora la do per chiusa questa issue.
Soltanto una cosa: prima di fare il push da linea di comando, assicurati di aver chiuso Matlab, altrimenti carichi nella repository anche i file ~ che sono file di matlab temporanei.

**Comment by giudisciacca** [comment]
@andreafarina : perfetto! Sì, mi ero accorto dei file temporanei, ma pensavo non fossero messi sotto source control. Sarò più attento la prossima volta. Grazie
