### ISSUE TITLE
Quantify DOT - heterogeneities

### ISSUE THREAD

**Issue by andreafarina** [andreafarina/SOLUS#7]
Ho fatto il merge della branch FEM_integration nella master. Dovresti modificare il quantify DOT per gestire la singola inclusione con mua e mus. Prima le due erano considerate 2 heterogeneità, adesso è una sola (vedi precedente commit nella branch FEM_integration).

**Comment by edoardo-ferocino** [comment]
Quindi adesso nella struttura REC, c'è solo REC.opt.hete1 e non più REC.opt.hete2. 
Se così è il bug è facilmente risolto cambiando in QuantifyDOT, come ingresso a QuantifyX nel caso 'mus', da REC.opt.hete2 a REC.opt.hete1. Ho provato a lanciare una sim sull'esempio StandardMuaMus e funziona. Se vuoi provare a vedere se funziona anche tu prima che faccia il commit dimmi pure.

In pratica ho sostuituito
if any(strcmpi(REC.solver.variables,'mus'))
    Q.mus = QuantifyX(REC.grid,REC.opt.muspB,REC.opt.bmusp,...
    ref_true,REC.opt.hete**2**.c,REC.opt.Musp);
end
con
if any(strcmpi(REC.solver.variables,'mus'))
    Q.mus = QuantifyX(REC.grid,REC.opt.muspB,REC.opt.bmusp,...
    ref_true,REC.opt.hete**1**.c,REC.opt.Musp);
end

**Comment by andreafarina** [comment]
Se hai già provato mi fido! Fai pure il commit!
